### ISSUE TITLE
Double tools menu

### ISSUE THREAD

**Issue by Andreotti100** [manicken/arduinoPrefsSaver#1]
After installing this (could have saved me some time if you explained how), the Tools->Board settings menu shows all items double.

**Comment by manicken** [comment]
Yes I forgot the install instructions, I'm sorry for that but I will soon update the readme. 
The install instructions is the same as https://github.com/manicken/arduinoAPIwebserver
Also the double menu is fixed for now by 
make the editor unfocused (click outside).
Its the internal structure of the Arduino source code that makes this problem appear. 
I will look into this problem.

**Comment by manicken** [comment]
it was easier than I thought
but now the double items is fixed
also added a feature that that auto close other editors when open new or existing sketch
the readme is updated to include install instructions + more information

**Comment by Andreotti100** [comment]
That's really good news!
Just tested it, working great now, thanks for your good work!

**Comment by manicken** [comment]
If you want faster recompile when switching between sketches.
Try
https://github.com/manicken/arduinoIDEsketchBuildPath
That makes the build output to a sub folder inside the sketch, instead of using the temp folder that is deleted every time a sketch is closed.
More info is on the github page.

**Comment by Andreotti100** [comment]
Just tested that also. Works great too. I don't know if I'am going to use this much, but I can see the potential.
The real headache saver is the prefSaver :-) Why is that not standard functionality from the Arduino IDE creators it self ???

**Comment by manicken** [comment]
Fixed
